name: 'main artifact'
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '11.3.Rel1'

    - name: Install Python dependencies
      run: python -m pip install --upgrade pip crcmod

    - name: Checkout
      uses: actions/checkout@v3

    - name: Submodules
      run: git submodule update --init --recursive --depth 1

    - name: Make
      run:  make

    - name: size
      run:  arm-none-eabi-size firmware

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: firmware*.bin
        
    - name: rename
      run: mv firmware.packed.bin firmware_packed${{ github.event.release.tag_name }}.bin
  
    - name: Get the date
      id: date
 #    run: echo "::set-output name=date::$(date +'%A %d.%m.%Y %H:%M - %Z')" #>> $GITHUB_OUTPUT
 #    run: echo "::set-output name=date::$(date +'%Y-%m-%d')"  
      run: echo "date=$(date +'%A %d.%m.%Y %H:%M - %Z')" >> $GITHUB_OUTPUT

    - name: 'Add unpacked FW to release'
      uses: svenstaro/upload-release-action@v2
      with:
        file: firmware.bin
        asset_name: ${{ format('firmware_raw_0.{0}.bin', github.run_number) }}
        tag: ${{ format('release-{0}', github.run_number) }}
        release_name: ${{ format('Build 0.{0}, {1}', github.run_number, steps.date.outputs.date) }}
  
    - name: 'Add packed FW to release'
      uses: svenstaro/upload-release-action@v2
      with:
        file: firmware_packed${{ github.event.release.tag_name }}.bin
        asset_name: ${{ format('firmware_packed_0.{0}.bin', github.run_number) }}
        tag: ${{ format('release-{0}', github.run_number) }}
        release_name: ${{ format('Build 0.{0}, {1}', github.run_number, steps.date.outputs.date) }}
